name: Unit Tests & Lint

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Rubocop lab1
        run: cd converter_ckf/ && bundle exec rubocop
      - name: Rubocop lab2
        run: cd work_with_csv/ && bundle exec rubocop
      - name: RSpec laba 1
        run: cd converter_ckf/ && bundle exec rspec
      - name: RSpec laba 2
        run: cd work_with_csv/ && bundle exec rspec
